package com.example.rewards.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import lombok.*;


@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder                   //simplifying object creation
public class Customer {

    @Id                       //primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)        //automatically generated by db
    private Long id;

    private String firstName;
    private String lastName;
    private String email;
}
